- hosts: webservers
  become: true
  vars:
   pkg_name: apache2
   dest_path: /var/www/html
  tasks:
  - name: Update repo
    command: apt update -y
  - name: Install a package {{pkg_name}}
    apt: name={{pkg_name}} state=present
  - name: Start {{pkg_name}} service
    service: name={{pkg_name}} state=started
  - name: Deploy index.html file
    copy: src=index.html dest={{dest_path}}
  - name: Restart {{pkg_name}} server
    service: name={{pkg_name}} state=restarted
