- hosts: webservers
  become: true
  tasks:
  - name: Update repo
    command: apt update -y
  - name: Install a package apache2
    apt: name=apache2 state=present
  - name: Start apache2 service
    service: name=apache2 state=started
  - name: Deploy index.html file
    copy: src=index.html dest=/var/www/html
  - name: Restart apache2 server
    service: name=apache2 state=restarted
